---

- name: verify fabric network
  hosts: allnodes
  user: "{{ fabric.ssh_user }}"
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - name: Display docker networks
      shell: |
        docker network inspect bridge > /tmp/docker_ip/{{ hostvars[inventory_hostname].inter_name }}
      register: dockercontainers
    - fetch: 
        src: /tmp/docker_ip/{{ hostvars[inventory_hostname].inter_name }}
        dest: /tmp/docker_ip/
        flat: yes
    - copy:
        src: /tmp/docker_ip/
        dest: /home/ubuntu/dbi/ansible/docker_ip/
        owner: ubuntu
        mode: u=rw,g=r,o=r
    - name: Create network.yaml
      hosts: builders
      shell: >-
        sh sednet.sh
      args:
        chdir: /home/ubuntu/dbi/ansible/docker_ip
